name: App Deployment
on:
  pull_request:
    paths:
      - apps/**
    branches:
      - main
    types:
      - closed
jobs:
  deploy_when_merged:
    if: ${{ github.event.pull_request.merged == true && github.repository_owner == 'billybillydev' && contains(github.event.pull_request.labels.*.name,'app') }}
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.2.55
      - run: flyctl deploy ./apps/www
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}