name: CLI Deploy
on:
  pull_request:
    branches:
      - main
    types: closed
jobs:
  deploy_when_merged:
    if: ${{ github.event.pull_request.merged == true && github.repository_owner == 'billybillydev' && contains(github.event.pull_request.labels.*.name,'cli') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.1

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          version: 8.6.1
          node-version: 18
          cache: "pnpm"

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Build the package
        run: pnpm build:cli

      - name: Publish package
        run: pnpm pub:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_ENV: "production"
